// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"backend/internal/context"
	"backend/internal/handlers"
	"github.com/mazrean/kessoku"
)

func RoleAPIWithInterface(context0 *context.Context) *handlers.RoleHandler {
	roleHandler := kessoku.Provide(handlers.NewRoleHandler).Fn()(context0)
	return roleHandler
}
