// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFileTag(ctx context.Context, arg AddFileTagParams) error
	AddUserFavorite(ctx context.Context, arg AddUserFavoriteParams) error
	CheckFileIsFavorite(ctx context.Context, arg CheckFileIsFavoriteParams) (bool, error)
	CheckUserHasFolderPermission(ctx context.Context, arg CheckUserHasFolderPermissionParams) (bool, error)
	CheckUserHasPermission(ctx context.Context, arg CheckUserHasPermissionParams) (bool, error)
	CreateActivityLogEntry(ctx context.Context, arg CreateActivityLogEntryParams) (*ActivityLog, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	CreateCodec(ctx context.Context, name pgtype.Text) (*Codec, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (*File, error)
	CreateFileAttribute(ctx context.Context, arg CreateFileAttributeParams) (*FileAttribute, error)
	CreateFileComment(ctx context.Context, arg CreateFileCommentParams) (*FileComment, error)
	CreateFileMetadata(ctx context.Context, arg CreateFileMetadataParams) (*FileMetadatum, error)
	CreateFilePermission(ctx context.Context, arg CreateFilePermissionParams) (*FilePermission, error)
	CreateFileVersion(ctx context.Context, arg CreateFileVersionParams) (*FileVersion, error)
	CreateFolder(ctx context.Context, folder pgtype.Text) (*Folder, error)
	CreateFolderAttribute(ctx context.Context, arg CreateFolderAttributeParams) (*FolderAttribute, error)
	CreateFolderPermission(ctx context.Context, arg CreateFolderPermissionParams) (*FolderPermission, error)
	CreateFormat(ctx context.Context, codec pgtype.Text) (*Format, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (*Role, error)
	CreateScheduledTask(ctx context.Context, arg CreateScheduledTaskParams) (*ScheduledTask, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (*UserSession, error)
	CreateStorageLocation(ctx context.Context, arg CreateStorageLocationParams) (*StorageLocation, error)
	CreateTType(ctx context.Context, arg CreateTTypeParams) (*TType, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (*Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteAllFileComments(ctx context.Context, fileID pgtype.Int4) error
	DeleteAllFileVersions(ctx context.Context, fileID pgtype.Int4) error
	DeleteCategory(ctx context.Context, id int32) error
	DeleteCodec(ctx context.Context, id int32) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteFile(ctx context.Context, id int32) error
	DeleteFileAttribute(ctx context.Context, id int32) error
	DeleteFileAttributeByFileID(ctx context.Context, fileID pgtype.Int4) error
	DeleteFileComment(ctx context.Context, id int32) error
	DeleteFileMetadata(ctx context.Context, fileID pgtype.Int4) error
	DeleteFilePermission(ctx context.Context, id int32) error
	DeleteFileVersion(ctx context.Context, id int32) error
	DeleteFolder(ctx context.Context, id int32) error
	DeleteFolderAttribute(ctx context.Context, id int32) error
	DeleteFolderAttributeByFolderID(ctx context.Context, folderID pgtype.Int4) error
	DeleteFolderPermission(ctx context.Context, id int32) error
	DeleteFormat(ctx context.Context, id int32) error
	DeleteOldActivityLog(ctx context.Context, createdAt pgtype.Timestamp) error
	DeleteRole(ctx context.Context, id int32) error
	DeleteScheduledTask(ctx context.Context, id int32) error
	DeleteSession(ctx context.Context, token string) error
	DeleteStorageLocation(ctx context.Context, id int32) error
	DeleteTType(ctx context.Context, id int32) error
	DeleteTag(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteUserFilePermission(ctx context.Context, arg DeleteUserFilePermissionParams) error
	DeleteUserFolderPermission(ctx context.Context, arg DeleteUserFolderPermissionParams) error
	DeleteUserSessions(ctx context.Context, userID pgtype.Int4) error
	GetActivityLogEntry(ctx context.Context, id int32) (*ActivityLog, error)
	GetCategory(ctx context.Context, id int32) (*Category, error)
	GetCategoryByKey(ctx context.Context, catKey pgtype.Text) (*Category, error)
	GetCodec(ctx context.Context, id int32) (*Codec, error)
	GetCodecByName(ctx context.Context, name pgtype.Text) (*Codec, error)
	GetFile(ctx context.Context, id int32) (*File, error)
	GetFileAttribute(ctx context.Context, id int32) (*FileAttribute, error)
	GetFileAttributeByFileID(ctx context.Context, fileID pgtype.Int4) (*FileAttribute, error)
	GetFileComment(ctx context.Context, id int32) (*FileComment, error)
	GetFileMetadata(ctx context.Context, fileID pgtype.Int4) (*FileMetadatum, error)
	GetFilePermission(ctx context.Context, id int32) (*FilePermission, error)
	GetFilePermissionsByFileId(ctx context.Context, fileID pgtype.Int4) ([]*FilePermission, error)
	GetFileVersion(ctx context.Context, id int32) (*FileVersion, error)
	GetFileVersionByNumber(ctx context.Context, arg GetFileVersionByNumberParams) (*FileVersion, error)
	GetFileVersionsByFileId(ctx context.Context, fileID pgtype.Int4) ([]*FileVersion, error)
	GetFileWithMetadata(ctx context.Context, id int32) (*GetFileWithMetadataRow, error)
	GetFolder(ctx context.Context, id int32) (*Folder, error)
	GetFolderAttribute(ctx context.Context, id int32) (*FolderAttribute, error)
	GetFolderAttributeByFolderID(ctx context.Context, folderID pgtype.Int4) (*FolderAttribute, error)
	GetFolderPermission(ctx context.Context, id int32) (*FolderPermission, error)
	GetFolderPermissionsByFolderId(ctx context.Context, folderID pgtype.Int4) ([]*FolderPermission, error)
	GetFolderWithAttributes(ctx context.Context, id int32) (*GetFolderWithAttributesRow, error)
	GetFormat(ctx context.Context, id int32) (*Format, error)
	GetFormatByCodec(ctx context.Context, codec pgtype.Text) (*Format, error)
	GetLatestFileVersion(ctx context.Context, fileID pgtype.Int4) (*FileVersion, error)
	GetLatestFileVersionByFileId(ctx context.Context, fileID pgtype.Int4) (*FileVersion, error)
	GetRole(ctx context.Context, id int32) (*Role, error)
	GetScheduledTask(ctx context.Context, id int32) (*ScheduledTask, error)
	GetScheduledTaskByName(ctx context.Context, name string) (*ScheduledTask, error)
	GetSession(ctx context.Context, arg GetSessionParams) (*UserSession, error)
	GetSessionByToken(ctx context.Context, token string) (*UserSession, error)
	GetStorageLocation(ctx context.Context, id int32) (*StorageLocation, error)
	GetStorageLocationByName(ctx context.Context, name string) (*StorageLocation, error)
	GetTType(ctx context.Context, id int32) (*TType, error)
	GetTTypeByKey(ctx context.Context, typeKey pgtype.Text) (*TType, error)
	GetTag(ctx context.Context, id int32) (*Tag, error)
	GetTagByName(ctx context.Context, name string) (*Tag, error)
	GetUser(ctx context.Context, id int32) (*User, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (*User, error)
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	GetUserFavorite(ctx context.Context, arg GetUserFavoriteParams) (*UserFavorite, error)
	GetUserFilePermission(ctx context.Context, arg GetUserFilePermissionParams) (*FilePermission, error)
	GetUserFolderPermission(ctx context.Context, arg GetUserFolderPermissionParams) (*FolderPermission, error)
	ListActiveScheduledTasks(ctx context.Context) ([]*ScheduledTask, error)
	ListActiveStorageLocations(ctx context.Context) ([]*StorageLocation, error)
	ListActivityByAction(ctx context.Context, arg ListActivityByActionParams) ([]*ActivityLog, error)
	ListActivityByTarget(ctx context.Context, arg ListActivityByTargetParams) ([]*ActivityLog, error)
	ListActivityLog(ctx context.Context, arg ListActivityLogParams) ([]*ActivityLog, error)
	ListCategories(ctx context.Context) ([]*Category, error)
	ListCategoriesByType(ctx context.Context, tTypeID pgtype.Int4) ([]*Category, error)
	ListCodecs(ctx context.Context) ([]*Codec, error)
	ListDueScheduledTasks(ctx context.Context) ([]*ScheduledTask, error)
	ListFileAttributes(ctx context.Context) ([]*FileAttribute, error)
	ListFileAttributesByCodec(ctx context.Context, codecID pgtype.Int4) ([]*FileAttribute, error)
	ListFileAttributesByFormat(ctx context.Context, format pgtype.Text) ([]*FileAttribute, error)
	ListFileComments(ctx context.Context, fileID pgtype.Int4) ([]*FileComment, error)
	ListFilePermissions(ctx context.Context, fileID pgtype.Int4) ([]*FilePermission, error)
	ListFileVersions(ctx context.Context, fileID pgtype.Int4) ([]*FileVersion, error)
	ListFiles(ctx context.Context) ([]*File, error)
	ListFilesByFolder(ctx context.Context, folderID pgtype.Int4) ([]*File, error)
	ListFilesByMimeType(ctx context.Context, mimeType pgtype.Text) ([]*File, error)
	ListFilesBySize(ctx context.Context, arg ListFilesBySizeParams) ([]*File, error)
	ListFilesByTag(ctx context.Context, tagID int32) ([]*File, error)
	ListFolderAttributes(ctx context.Context) ([]*FolderAttribute, error)
	ListFolderPermissions(ctx context.Context, folderID pgtype.Int4) ([]*FolderPermission, error)
	ListFolders(ctx context.Context) ([]*Folder, error)
	ListFormats(ctx context.Context) ([]*Format, error)
	ListRoles(ctx context.Context) ([]*Role, error)
	ListScheduledTasks(ctx context.Context) ([]*ScheduledTask, error)
	ListScheduledTasksByType(ctx context.Context, type_ string) ([]*ScheduledTask, error)
	ListStorageLocations(ctx context.Context) ([]*StorageLocation, error)
	ListStorageLocationsByType(ctx context.Context, type_ string) ([]*StorageLocation, error)
	ListSubcategories(ctx context.Context, categoryID pgtype.Int4) ([]*Category, error)
	ListTTypes(ctx context.Context) ([]*TType, error)
	ListTags(ctx context.Context) ([]*Tag, error)
	ListTagsByCreator(ctx context.Context, createdBy pgtype.Int4) ([]*Tag, error)
	ListTagsForFile(ctx context.Context, fileID int32) ([]*Tag, error)
	ListUserActivityLog(ctx context.Context, arg ListUserActivityLogParams) ([]*ActivityLog, error)
	ListUserComments(ctx context.Context, userID pgtype.Int4) ([]*FileComment, error)
	ListUserFavorites(ctx context.Context, userID int32) ([]*File, error)
	ListUserFolderPermissions(ctx context.Context, userID pgtype.Int4) ([]*FolderPermission, error)
	ListUserPermissions(ctx context.Context, userID pgtype.Int4) ([]*FilePermission, error)
	ListUserSessions(ctx context.Context, userID pgtype.Int4) ([]*UserSession, error)
	ListUsers(ctx context.Context) ([]*User, error)
	RemoveAllUserFavorites(ctx context.Context, userID int32) error
	RemoveFileTag(ctx context.Context, arg RemoveFileTagParams) error
	RemoveUserFavorite(ctx context.Context, arg RemoveUserFavoriteParams) error
	ToggleStorageLocationActive(ctx context.Context, id int32) (*StorageLocation, error)
	ToggleTaskStatus(ctx context.Context, id int32) (*ScheduledTask, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
	UpdateCodec(ctx context.Context, arg UpdateCodecParams) (*Codec, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (*File, error)
	UpdateFileAccess(ctx context.Context, fileID pgtype.Int4) (*FileMetadatum, error)
	UpdateFileAttribute(ctx context.Context, arg UpdateFileAttributeParams) (*FileAttribute, error)
	UpdateFileComment(ctx context.Context, arg UpdateFileCommentParams) (*FileComment, error)
	UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (*FileMetadatum, error)
	UpdateFilePermission(ctx context.Context, arg UpdateFilePermissionParams) (*FilePermission, error)
	UpdateFolder(ctx context.Context, arg UpdateFolderParams) (*Folder, error)
	UpdateFolderAttribute(ctx context.Context, arg UpdateFolderAttributeParams) (*FolderAttribute, error)
	UpdateFolderAttributeByFolderID(ctx context.Context, arg UpdateFolderAttributeByFolderIDParams) (*FolderAttribute, error)
	UpdateFolderPermission(ctx context.Context, arg UpdateFolderPermissionParams) (*FolderPermission, error)
	UpdateFormat(ctx context.Context, arg UpdateFormatParams) (*Format, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	UpdateScheduledTask(ctx context.Context, arg UpdateScheduledTaskParams) (*ScheduledTask, error)
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) (*UserSession, error)
	UpdateStorageLocation(ctx context.Context, arg UpdateStorageLocationParams) (*StorageLocation, error)
	UpdateTType(ctx context.Context, arg UpdateTTypeParams) (*TType, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (*Tag, error)
	UpdateTaskLastRun(ctx context.Context, arg UpdateTaskLastRunParams) (*ScheduledTask, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
